@php
    $template = $reservation->service->documentTemplate;
    $document = $reservation->document;
    $canPrepare = $reservation->status->canPrepareDocument();
@endphp
<section class="card dashboard-panel reservation-panel mt-4" aria-labelledby="document-heading">
    <h2 id="document-heading">Official Document Preparation</h2>
    <p class="app-note">Prepare the Barangay Calayo document for printing, signing and physical issuance. Preparation does not change the request status.</p>
    @if($document)
        <h3 class="h6">Document status: Prepared</h3>
        <dl class="reservation-summary">
            <div><dt>Generated</dt><dd>{{ $document->generated_at->timezone('Asia/Manila')->format('F j, Y, g:i A') }} · Philippine time</dd></div>
            <div><dt>Generated by</dt><dd>{{ $document->generator?->name ?? 'Former Admin account' }}</dd></div>
            <div><dt>Source template</dt><dd class="text-break">{{ $document->template_filename }}</dd></div>
        </dl>
        <a class="btn btn-outline-primary mb-3" href="{{ route('admin.reservations.document.download', $reservation) }}">Download Ready-to-Print DOCX</a>
        @if($template && ! hash_equals($document->template_revision, $template->revision()))
            <p class="alert alert-warning" role="status">Official template has changed since this document was generated. The existing document is preserved.</p>
        @endif
        @if($reservation->status === \App\Enums\ReservationStatus::Completed)
            <p class="app-note">This completed document is a historical record. Regeneration is unavailable.</p>
        @endif
    @else
        <p class="h6">Document status: Not prepared</p>
    @endif
    @if(! $template)
        <p>No official document template has been uploaded for this Service.</p>
        <a class="btn btn-outline-secondary" href="{{ route('admin.services.edit', $reservation->service) }}">Edit Service</a>
    @else
        <p class="text-break"><strong>Current official template:</strong> {{ $template->original_filename }} · {{ $template->format() }}</p>
        @if($template->format() === 'PDF')
            <p>Automatic document preparation is available for DOCX templates only. This PDF remains available as the official static template/reference.</p>
            <a class="btn btn-outline-secondary" href="{{ route('admin.services.template.download', $reservation->service) }}">Download Official Template</a>
        @elseif(! $canPrepare)
            <p class="app-note mb-0">Preparation is available only for Approved or Ready for Pickup requests.</p>
        @else
            <h3 class="h6 mt-3">Resident data preview</h3>
            <p class="app-note">Review these values before preparing. Only fields used in the template are inserted. Missing values used by the template will block preparation.</p>
            <dl class="reservation-summary">
                @foreach(\App\Services\DocumentMergeFields::LABELS as $field => $label)
                    <div><dt>{{ $label }}</dt><dd class="text-break">{{ filled($mergeValues[$field]) ? $mergeValues[$field] : 'Not provided' }}</dd></div>
                @endforeach
            </dl>
            <form method="POST" action="{{ route('admin.reservations.document.store', $reservation) }}" data-service-submit>
                @csrf
                <button class="btn btn-primary" type="submit" data-saving-label="Preparing…">{{ $document ? 'Regenerate Document' : 'Prepare Ready-to-Print Document' }}</button>
            </form>
        @endif
    @endif
</section>
